import { Blog } from "../helpers/types/Blogs";

export const BLOGS: Array<Blog> = [
  {
    id: 1,
    title: "Revision of Autol Sub in L Patella, Extern Approach",
    content: "Nontraumatic rupture of other tendon",
    createdAt: "10/19/2021",
    image: "http://dummyimage.com/104x100.png/ff4444/ffffff",
  },
  {
    id: 2,
    title: "Removal of Synth Sub from R Tarsal, Perc Endo Approach",
    content: "Tuberculosis of other specified joint, unspecified",
    createdAt: "4/8/2022",
    image: "http://dummyimage.com/214x100.png/ff4444/ffffff",
  },
  {
    id: 3,
    title: "Excision of Left Basilic Vein, Open Approach, Diagnostic",
    content: "Unspecified visual disturbance",
    createdAt: "11/25/2022",
    image: "http://dummyimage.com/151x100.png/ff4444/ffffff",
  },
  {
    id: 4,
    title: "Change Bandage on Left Upper Arm",
    content: "Unspecified anomaly of tooth position",
    createdAt: "6/4/2021",
    image: "http://dummyimage.com/148x100.png/5fa2dd/ffffff",
  },
  {
    id: 5,
    title: "Stereotactic Particulate Radiosurgery of Thorax Lymphatics",
    content: "Accidental poisoning by fumigants",
    createdAt: "11/15/2021",
    image: "http://dummyimage.com/102x100.png/dddddd/000000",
  },
  {
    id: 6,
    title: "MRI of L Forearm using Oth Contrast",
    content:
      "Other named variants of lymphosarcoma and reticulosarcoma,intrathoracic lymph nodes",
    createdAt: "6/20/2021",
    image: "http://dummyimage.com/148x100.png/cc0000/ffffff",
  },
  {
    id: 7,
    title: "Drainage of Right Pleural Cavity, Open Approach, Diagnostic",
    content:
      "Closed fracture of vault of skull with other and unspecified intracranial hemorrhage, with prolonged [more than 24 hours] loss of consciousness, without return to pre-existing conscious level",
    createdAt: "2/24/2022",
    image: "http://dummyimage.com/223x100.png/5fa2dd/ffffff",
  },
  {
    id: 8,
    title: "CT Scan of Cisterna using Oth Contrast, Unenh, Enhance",
    content: "Malignant neoplasm of long bones of lower limb",
    createdAt: "7/18/2021",
    image: "http://dummyimage.com/233x100.png/5fa2dd/ffffff",
  },
  {
    id: 9,
    title: "Bypass Innom Art to Low Arm Vein w Nonaut Sub, Open",
    content: "Closed dislocation, thoracic vertebra",
    createdAt: "10/21/2021",
    image: "http://dummyimage.com/200x100.png/ff4444/ffffff",
  },
  {
    id: 10,
    title: "Introduction of Local Anesth into Periton Cav, Perc Approach",
    content: "Other specified symptoms associated with female genital organs",
    createdAt: "3/30/2022",
    image: "http://dummyimage.com/173x100.png/dddddd/000000",
  },
  {
    id: 11,
    title: "Beam Radiation of Face Skin using Photons 1 - 10 MeV",
    content: "Child neglect (nutritional)",
    createdAt: "4/8/2021",
    image: "http://dummyimage.com/220x100.png/5fa2dd/ffffff",
  },
  {
    id: 12,
    title: "Drainage of Left Parietal Bone, Percutaneous Approach",
    content: "Open wound of wrist, with tendon involvement",
    createdAt: "5/4/2022",
    image: "http://dummyimage.com/132x100.png/5fa2dd/ffffff",
  },
  {
    id: 13,
    title: "Removal of Radioactive Element from Resp Tract, Via Opening",
    content:
      "Encounter for hearing examination following failed hearing screening",
    createdAt: "8/18/2022",
    image: "http://dummyimage.com/186x100.png/5fa2dd/ffffff",
  },
  {
    id: 14,
    title: "Reposition Left Glenoid Cavity, Open Approach",
    content:
      "Infection with drug-resistant microorganisms, unspecified, with multiple drug resistance",
    createdAt: "10/30/2021",
    image: "http://dummyimage.com/123x100.png/dddddd/000000",
  },
  {
    id: 15,
    title: "Destruction of Left Posterior Tibial Artery, Open Approach",
    content: "Open wound of gum (alveolar process), complicated",
    createdAt: "2/26/2022",
    image: "http://dummyimage.com/216x100.png/ff4444/ffffff",
  },
  {
    id: 16,
    title: "Extraction of Thoracic Nerve, Perc Endo Approach",
    content: "Lymphocytopenia",
    createdAt: "9/6/2021",
    image: "http://dummyimage.com/169x100.png/ff4444/ffffff",
  },
  {
    id: 17,
    title: "Fluoroscopy of L Up Extrem Art using Oth Contrast",
    content: "Injury to unspecified pelvic organ, with open wound into cavity",
    createdAt: "7/8/2021",
    image: "http://dummyimage.com/155x100.png/ff4444/ffffff",
  },
  {
    id: 18,
    title: "Drainage of Right Shoulder Joint, Open Approach, Diagnostic",
    content:
      '"Light-for-dates" without mention of fetal malnutrition, 1,500- 1,749 grams',
    createdAt: "6/2/2021",
    image: "http://dummyimage.com/104x100.png/5fa2dd/ffffff",
  },
  {
    id: 19,
    title: "Dilation of R Ant Tib Art with 3 Drug-elut, Perc Approach",
    content:
      "Failed forceps or vacuum extractor, unspecified, unspecified as to episode of care or not applicable",
    createdAt: "9/29/2021",
    image: "http://dummyimage.com/170x100.png/ff4444/ffffff",
  },
  {
    id: 20,
    title: "Drainage of Left Maxillary Sinus, Percutaneous Approach",
    content: "Severe sepsis",
    createdAt: "1/26/2022",
    image: "http://dummyimage.com/201x100.png/ff4444/ffffff",
  },
  {
    id: 21,
    title: "Drainage of Left Mastoid Sinus, Percutaneous Approach",
    content: "Attention to colostomy",
    createdAt: "2/12/2022",
    image: "http://dummyimage.com/211x100.png/ff4444/ffffff",
  },
  {
    id: 22,
    title: "Supplement Left Atrium with Nonaut Sub, Perc Approach",
    content: "Personal history of nutritional deficiency",
    createdAt: "8/20/2021",
    image: "http://dummyimage.com/162x100.png/dddddd/000000",
  },
  {
    id: 23,
    title: "Revision of Int Fix in L Tarsal, Open Approach",
    content:
      "Noncollision motor vehicle traffic accident while boarding or alighting injuring passenger on motorcycle",
    createdAt: "10/12/2022",
    image: "http://dummyimage.com/198x100.png/5fa2dd/ffffff",
  },
  {
    id: 24,
    title: "Drainage of Perineum Skin, External Approach, Diagnostic",
    content: "Open dislocation, first cervical vertebra",
    createdAt: "3/7/2022",
    image: "http://dummyimage.com/114x100.png/5fa2dd/ffffff",
  },
  {
    id: 25,
    title: "Excision of Right Tibia, Perc Endo Approach, Diagn",
    content: "Other disorders of coccyx",
    createdAt: "8/8/2021",
    image: "http://dummyimage.com/193x100.png/ff4444/ffffff",
  },
  {
    id: 26,
    title: "Revision of Synth Sub in R Knee Jt, Femoral, Perc Approach",
    content: "Accidental poisoning by hormones and synthetic substitutes",
    createdAt: "5/1/2021",
    image: "http://dummyimage.com/186x100.png/5fa2dd/ffffff",
  },
  {
    id: 27,
    title: "Insertion of Infusion Device into R Knee, Perc Approach",
    content: "Unspecified infective arthritis, pelvic region and thigh",
    createdAt: "2/3/2022",
    image: "http://dummyimage.com/165x100.png/5fa2dd/ffffff",
  },
  {
    id: 28,
    title: "Insertion of Artificial Sphincter into Urethra, Endo",
    content:
      "Fetal hematologic conditions, antepartum condition or complication",
    createdAt: "2/21/2022",
    image: "http://dummyimage.com/128x100.png/dddddd/000000",
  },
  {
    id: 29,
    title: "Excision of L Ankle Bursa/Lig, Perc Endo Approach, Diagn",
    content: "Other cystostomy",
    createdAt: "7/18/2022",
    image: "http://dummyimage.com/214x100.png/5fa2dd/ffffff",
  },
  {
    id: 30,
    title: "Excision of R Low Lobe Bronc, Perc Endo Approach, Diagn",
    content: "Explosion, fire, or burning in watercraft injuring swimmer",
    createdAt: "4/5/2021",
    image: "http://dummyimage.com/153x100.png/ff4444/ffffff",
  },
];
